root_dir = '../../../..'
node_modules_dir = "#{root_dir}/node_modules"

require_relative "#{node_modules_dir}/react-native/scripts/react_native_pods"
require_relative "#{node_modules_dir}/@react-native-community/cli-platform-ios/native_modules"

platform :ios, '13.0'

inhibit_all_warnings!

target 'HelloWorld' do
  config = use_native_modules!

  use_react_native!(:path => "#{node_modules_dir}/react-native")

  target 'HelloWorldTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({
    'Flipper' => '>= 0.69.0'
  })
  post_install do |installer|
    flipper_post_install(installer)
  end
end
